import { useState, useCallback } from "react";

const EMOJIS = ["🥩","🐟","🦐","🦑","🍗","🦀","🐙","🥚","🧆","🍖","🐄","🐖"];
const COLORS = ["#FF6B35","#E91E8C","#00B4D8","#FFB703","#7C3AED","#10B981","#F59E0B","#EF4444","#06B6D4","#84CC16"];

let nextId = 1;

// ── shared calc helper ──────────────────────────────────────────────
function calcItem({ price, iceWater, otherWaste, quantity }) {
  const totalWasteG  = iceWater + otherWaste;
  const yieldG       = 1000 - totalWasteG;
  const wastePercent = (totalWasteG / 1000) * 100;
  const yieldPercent = 100 - wastePercent;
  const effectiveRate = yieldPercent > 0 ? (price / yieldPercent) * 100 : 0;
  const totalCost    = price * quantity;
  const yieldKg      = (yieldPercent / 100) * quantity;
  const iceWaterKg   = (iceWater / 1000) * quantity;
  const otherWasteKg = (otherWaste / 1000) * quantity;
  const wasteCost    = totalCost * (wastePercent / 100);
  return { totalWasteG, yieldG, wastePercent, yieldPercent, effectiveRate,
           totalCost, yieldKg, iceWaterKg, otherWasteKg, wasteCost };
}

// ── PDF generator (pure JS, no deps) ────────────────────────────────
function generatePDF(rows) {
  const date = new Date().toLocaleDateString("si-LK", { year:"numeric", month:"long", day:"numeric" });
  const grandTotal = rows.reduce((s,r) => s + (r.calc?.totalCost || 0), 0);
  const grandWaste = rows.reduce((s,r) => s + (r.calc?.wasteCost || 0), 0);
  const grandYield = rows.reduce((s,r) => s + (r.calc?.yieldKg  || 0), 0);

  // Build HTML for the report
  const rowsHTML = rows.map(r => {
    const c = r.calc;
    if (!c || !r.price) return `
      <tr>
        <td>${r.emoji} ${r.name}</td>
        <td colspan="7" style="color:#999;font-style:italic;text-align:center;">Data නැහැ</td>
      </tr>`;
    return `
      <tr>
        <td><strong>${r.emoji} ${r.name}</strong></td>
        <td>රු. ${r.price.toLocaleString()}</td>
        <td>${r.iceWater}g / ${r.otherWaste}g</td>
        <td>${c.wastePercent.toFixed(1)}%</td>
        <td style="color:#e74c3c;font-weight:700;">රු. ${Math.round(c.effectiveRate).toLocaleString()}</td>
        <td>${r.quantity ? r.quantity + " kg" : "-"}</td>
        <td>${r.quantity ? "රු. " + c.totalCost.toLocaleString() : "-"}</td>
        <td style="color:#e74c3c;">${r.quantity ? "රු. " + Math.round(c.wasteCost).toLocaleString() : "-"}</td>
      </tr>`;
  }).join("");

  const html = `<!DOCTYPE html>
<html lang="si">
<head>
<meta charset="UTF-8"/>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+Sinhala:wght@400;700&display=swap');
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family: 'Noto Sans Sinhala', Arial, sans-serif; background:#fff; color:#1a1a1a; padding: 32px; }
  .header { border-bottom: 3px solid #FF6B35; padding-bottom: 20px; margin-bottom: 28px; display:flex; justify-content:space-between; align-items:flex-end; }
  .header-left h1 { font-size: 26px; color: #FF6B35; font-weight: 800; letter-spacing:-1px; }
  .header-left p { color:#888; font-size:12px; margin-top:4px; }
  .header-right { text-align:right; font-size:12px; color:#888; }
  .header-right strong { display:block; font-size:14px; color:#333; }
  .summary { display:flex; gap:16px; margin-bottom:28px; }
  .sum-box { flex:1; padding:16px; border-radius:10px; text-align:center; }
  .sum-box .val { font-size:20px; font-weight:800; }
  .sum-box .lbl { font-size:11px; color:#888; margin-top:4px; }
  .sum-total { background:#fff8f5; border:2px solid #FF6B35; }
  .sum-waste  { background:#fff5f5; border:2px solid #e74c3c; }
  .sum-yield  { background:#f5fff8; border:2px solid #27ae60; }
  table { width:100%; border-collapse:collapse; font-size:12px; }
  thead tr { background:#FF6B35; color:#fff; }
  thead th { padding:10px 12px; text-align:left; font-weight:700; font-size:11px; }
  tbody tr:nth-child(even) { background:#fafafa; }
  tbody tr:hover { background:#fff3ee; }
  tbody td { padding:10px 12px; border-bottom:1px solid #f0f0f0; vertical-align:middle; }
  .footer { margin-top:28px; padding-top:16px; border-top:2px solid #eee; display:flex; justify-content:space-between; font-size:11px; color:#aaa; }
  @media print {
    body { padding: 16px; }
    .no-print { display:none; }
  }
</style>
</head>
<body>
  <div class="header">
    <div class="header-left">
      <h1>🥩 Waste Cost Report</h1>
      <p>මාළු / මස් — Waste & Effective Rate විශ්ලේෂණය</p>
    </div>
    <div class="header-right">
      <strong>${date}</strong>
      Generated by Meat Calculator
    </div>
  </div>

  <div class="summary">
    <div class="sum-box sum-total">
      <div class="val" style="color:#FF6B35;">රු. ${grandTotal.toLocaleString()}</div>
      <div class="lbl">මුළු වියදම</div>
    </div>
    <div class="sum-box sum-waste">
      <div class="val" style="color:#e74c3c;">රු. ${Math.round(grandWaste).toLocaleString()}</div>
      <div class="lbl">Waste Cost (නාස්ති)</div>
    </div>
    <div class="sum-box sum-yield">
      <div class="val" style="color:#27ae60;">${grandYield.toFixed(2)} kg</div>
      <div class="lbl">මුළු ලැබෙන Yield</div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Item</th>
        <th>කිලෝ මිල</th>
        <th>Ice / Other Waste</th>
        <th>Waste %</th>
        <th>Effective Rate</th>
        <th>ප්‍රමාණය</th>
        <th>මුළු වියදම</th>
        <th>Waste Cost</th>
      </tr>
    </thead>
    <tbody>
      ${rowsHTML}
    </tbody>
  </table>

  <div class="footer">
    <span>Meat & Seafood Waste Calculator</span>
    <span>මේ report එකෙන් waste නිසා නාස්ති වෙන මුදල් දැකගත හැකියි</span>
  </div>

  <script>window.onload = () => { window.print(); }</script>
</body>
</html>`;

  const blob = new Blob([html], { type: "text/html" });
  const url  = URL.createObjectURL(blob);
  const win  = window.open(url, "_blank");
  if (!win) alert("Popup blocked — please allow popups and try again.");
}

// ── InputField ────────────────────────────────────────────────────────
function InputField({ label, sublabel, placeholder, value, onChange, color, small }) {
  return (
    <div>
      <label style={{ display:"block", marginBottom:4 }}>
        <span style={{ fontSize: small ? 10 : 11, fontWeight:700, color:"#888", letterSpacing:1.2, textTransform:"uppercase" }}>{label}</span>
        {sublabel && <span style={{ fontSize:10, color:"#555", marginLeft:5 }}>{sublabel}</span>}
      </label>
      <input
        type="number" placeholder={placeholder} value={value}
        onChange={(e) => onChange(e.target.value)}
        style={{ width:"100%", background:"rgba(255,255,255,0.06)", border:"1.5px solid #2a2a2a",
          borderRadius:9, padding: small ? "8px 12px" : "10px 14px", color:"#fff",
          fontSize: small ? 13 : 15, fontWeight:600, outline:"none",
          boxSizing:"border-box", transition:"border-color 0.2s" }}
        onFocus={(e) => (e.target.style.borderColor = color)}
        onBlur={(e)  => (e.target.style.borderColor = "#2a2a2a")}
      />
    </div>
  );
}

// ── ItemCard ──────────────────────────────────────────────────────────
function ItemCard({ item, onRemove, onDataChange }) {
  const [pricePerKg,  setPricePerKg]  = useState("");
  const [iceWaterG,   setIceWaterG]   = useState("");
  const [otherWasteG, setOtherWasteG] = useState("");
  const [qty,         setQty]         = useState("");

  const update = (field, val, setter) => {
    setter(val);
    const vals = {
      price:      field === "price"      ? parseFloat(val) || 0 : parseFloat(pricePerKg)  || 0,
      iceWater:   field === "iceWater"   ? parseFloat(val) || 0 : parseFloat(iceWaterG)   || 0,
      otherWaste: field === "otherWaste" ? parseFloat(val) || 0 : parseFloat(otherWasteG) || 0,
      quantity:   field === "quantity"   ? parseFloat(val) || 0 : parseFloat(qty)         || 0,
    };
    onDataChange(item.id, vals);
  };

  const price      = parseFloat(pricePerKg)  || 0;
  const iceWater   = parseFloat(iceWaterG)   || 0;
  const otherWaste = parseFloat(otherWasteG) || 0;
  const quantity   = parseFloat(qty)         || 0;
  const c = calcItem({ price, iceWater, otherWaste, quantity });
  const hasAll = price > 0 && c.totalWasteG > 0;

  return (
    <div style={{ background:"rgba(255,255,255,0.03)", border:`1px solid ${item.color}33`,
        borderRadius:20, padding:"24px", position:"relative", overflow:"hidden",
        transition:"transform 0.2s, box-shadow 0.2s" }}
      onMouseEnter={(e) => { e.currentTarget.style.transform="translateY(-3px)"; e.currentTarget.style.boxShadow=`0 16px 36px ${item.color}22`; }}
      onMouseLeave={(e) => { e.currentTarget.style.transform="translateY(0)";    e.currentTarget.style.boxShadow="none"; }}
    >
      <div style={{ position:"absolute", top:-40, right:-40, width:120, height:120, borderRadius:"50%",
          background:`radial-gradient(circle, ${item.color}18, transparent 70%)`, pointerEvents:"none" }} />

      {/* Header */}
      <div style={{ display:"flex", alignItems:"center", justifyContent:"space-between", marginBottom:20 }}>
        <div style={{ display:"flex", alignItems:"center", gap:10 }}>
          <span style={{ fontSize:30 }}>{item.emoji}</span>
          <div>
            <div style={{ fontSize:20, fontWeight:700, color:"#fff", fontFamily:"'Noto Sans Sinhala',sans-serif" }}>{item.name}</div>
            {hasAll && <div style={{ fontSize:10, color:item.color, fontWeight:600 }}>Waste {c.wastePercent.toFixed(1)}% • Yield {c.yieldPercent.toFixed(1)}%</div>}
          </div>
        </div>
        <button onClick={() => onRemove(item.id)} style={{ background:"rgba(255,100,100,0.1)", border:"1px solid #ff6b6b33",
            color:"#ff6b6b", borderRadius:8, width:30, height:30, cursor:"pointer", fontSize:14,
            display:"flex", alignItems:"center", justifyContent:"center" }}
          onMouseEnter={(e) => (e.currentTarget.style.background="rgba(255,100,100,0.25)")}
          onMouseLeave={(e) => (e.currentTarget.style.background="rgba(255,100,100,0.1)")}
        >✕</button>
      </div>

      {/* Inputs */}
      <div style={{ display:"flex", flexDirection:"column", gap:10 }}>
        <InputField label="කිලෝ මිල" sublabel="(රු.)" placeholder="e.g. 3800"
          value={pricePerKg} onChange={(v) => update("price", v, setPricePerKg)} color={item.color} />
        <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:8 }}>
          <InputField label="Ice Water" sublabel="(g/kg)" placeholder="e.g. 250"
            value={iceWaterG} onChange={(v) => update("iceWater", v, setIceWaterG)} color={item.color} small />
          <InputField label="Skin/Bone" sublabel="(g/kg)" placeholder="e.g. 80"
            value={otherWasteG} onChange={(v) => update("otherWaste", v, setOtherWasteG)} color={item.color} small />
        </div>
        <InputField label="ප්‍රමාණය" sublabel="(kg)" placeholder="e.g. 5"
          value={qty} onChange={(v) => update("quantity", v, setQty)} color={item.color} />
      </div>

      {/* Results */}
      {hasAll && (
        <div style={{ marginTop:16, padding:14, background:`linear-gradient(135deg,${item.color}0e,${item.color}05)`,
            borderRadius:12, border:`1px solid ${item.color}1a` }}>
          {/* Bar */}
          <div style={{ display:"flex", height:8, borderRadius:4, overflow:"hidden", gap:2, marginBottom:6 }}>
            <div style={{ flex:c.yieldPercent, background:item.color }} />
            {iceWater  > 0 && <div style={{ flex:(iceWater/1000)*100,  background:"#4a9eff55" }} />}
            {otherWaste>0  && <div style={{ flex:(otherWaste/1000)*100,background:"#ff6b6b55" }} />}
          </div>
          <div style={{ display:"flex", gap:10, marginBottom:12, flexWrap:"wrap" }}>
            <span style={{ fontSize:9, color:item.color }}>■ Yield {c.yieldG}g</span>
            {iceWater  > 0 && <span style={{ fontSize:9, color:"#4a9eff" }}>■ Ice {iceWater}g</span>}
            {otherWaste> 0 && <span style={{ fontSize:9, color:"#ff6b6b" }}>■ Other {otherWaste}g</span>}
          </div>

          <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:"8px 14px" }}>
            <div>
              <div style={{ fontSize:9, color:"#555", fontWeight:700, letterSpacing:1, textTransform:"uppercase" }}>Effective Rate</div>
              <div style={{ fontSize:17, fontWeight:900, color:item.color }}>රු. {Math.round(c.effectiveRate).toLocaleString()}</div>
            </div>
            <div>
              <div style={{ fontSize:9, color:"#555", fontWeight:700, letterSpacing:1, textTransform:"uppercase" }}>Waste/kg Cost</div>
              <div style={{ fontSize:14, fontWeight:700, color:"#ff6b6b" }}>රු. {Math.round(price * c.wastePercent / 100).toLocaleString()}</div>
            </div>
          </div>

          {quantity > 0 && (
            <>
              <div style={{ height:1, background:"#ffffff08", margin:"12px 0" }} />
              <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:"8px 14px" }}>
                <div>
                  <div style={{ fontSize:9, color:"#555", fontWeight:700, letterSpacing:1, textTransform:"uppercase" }}>මුළු වියදම</div>
                  <div style={{ fontSize:13, fontWeight:700, color:"#ccc" }}>රු. {c.totalCost.toLocaleString()}</div>
                </div>
                <div>
                  <div style={{ fontSize:9, color:"#555", fontWeight:700, letterSpacing:1, textTransform:"uppercase" }}>ලැබෙන kg</div>
                  <div style={{ fontSize:13, fontWeight:700, color:item.color }}>{c.yieldKg.toFixed(2)}kg</div>
                </div>
              </div>
              <div style={{ marginTop:10, padding:"8px 12px", background:"rgba(255,107,107,0.07)",
                  border:"1px solid #ff6b6b1a", borderRadius:8, textAlign:"center" }}>
                <span style={{ color:"#666", fontSize:11 }}>Waste cost: </span>
                <span style={{ color:"#ff6b6b", fontWeight:900, fontSize:15 }}>රු. {Math.round(c.wasteCost).toLocaleString()}</span>
              </div>
            </>
          )}
        </div>
      )}
    </div>
  );
}

// ── AddItemModal ──────────────────────────────────────────────────────
function AddItemModal({ onAdd, onClose }) {
  const [name, setName] = useState("");
  const [emoji, setEmoji] = useState(EMOJIS[0]);
  const [color, setColor] = useState(COLORS[0]);
  const handleAdd = () => { if (!name.trim()) return; onAdd({ id: nextId++, name: name.trim(), emoji, color }); onClose(); };
  return (
    <div style={{ position:"fixed", inset:0, background:"rgba(0,0,0,0.75)", display:"flex",
        alignItems:"center", justifyContent:"center", zIndex:100, padding:20 }} onClick={onClose}>
      <div style={{ background:"#161616", border:"1px solid #2a2a2a", borderRadius:20, padding:28,
          width:"100%", maxWidth:360 }} onClick={(e) => e.stopPropagation()}>
        <h3 style={{ color:"#fff", margin:"0 0 20px", fontSize:18, fontWeight:800, fontFamily:"'Noto Sans Sinhala',sans-serif" }}>
          නව Item Add කරන්න
        </h3>
        <div style={{ marginBottom:16 }}>
          <label style={{ fontSize:11, fontWeight:700, color:"#888", letterSpacing:1.5, textTransform:"uppercase", display:"block", marginBottom:6 }}>නම</label>
          <input type="text" placeholder="e.g. හරක් මස්" value={name} autoFocus
            onChange={(e) => setName(e.target.value)} onKeyDown={(e) => e.key==="Enter" && handleAdd()}
            style={{ width:"100%", background:"rgba(255,255,255,0.06)", border:"1.5px solid #333",
              borderRadius:10, padding:"10px 14px", color:"#fff", fontSize:15, fontWeight:600,
              outline:"none", boxSizing:"border-box", fontFamily:"'Noto Sans Sinhala',sans-serif" }}
            onFocus={(e) => (e.target.style.borderColor = color)}
            onBlur={(e)  => (e.target.style.borderColor = "#333")}
          />
        </div>
        <div style={{ marginBottom:16 }}>
          <label style={{ fontSize:11, fontWeight:700, color:"#888", letterSpacing:1.5, textTransform:"uppercase", display:"block", marginBottom:8 }}>Icon</label>
          <div style={{ display:"flex", flexWrap:"wrap", gap:8 }}>
            {EMOJIS.map(e => (
              <button key={e} onClick={() => setEmoji(e)} style={{ width:38, height:38, borderRadius:10, fontSize:20,
                  background: emoji===e ? color+"33" : "rgba(255,255,255,0.05)",
                  border: emoji===e ? `2px solid ${color}` : "2px solid transparent", cursor:"pointer" }}>{e}</button>
            ))}
          </div>
        </div>
        <div style={{ marginBottom:20 }}>
          <label style={{ fontSize:11, fontWeight:700, color:"#888", letterSpacing:1.5, textTransform:"uppercase", display:"block", marginBottom:8 }}>Color</label>
          <div style={{ display:"flex", flexWrap:"wrap", gap:8 }}>
            {COLORS.map(c => (
              <button key={c} onClick={() => setColor(c)} style={{ width:28, height:28, borderRadius:"50%", background:c,
                  border: color===c ? "3px solid #fff" : "3px solid transparent", cursor:"pointer" }} />
            ))}
          </div>
        </div>
        <div style={{ display:"flex", alignItems:"center", gap:10, marginBottom:20,
            padding:"10px 14px", background:`${color}12`, border:`1px solid ${color}33`, borderRadius:10 }}>
          <span style={{ fontSize:24 }}>{emoji}</span>
          <span style={{ fontSize:16, fontWeight:700, color:"#fff", fontFamily:"'Noto Sans Sinhala',sans-serif" }}>{name || "නම..."}</span>
        </div>
        <div style={{ display:"flex", gap:10 }}>
          <button onClick={onClose} style={{ flex:1, padding:"11px", borderRadius:10,
              background:"rgba(255,255,255,0.05)", border:"1px solid #333",
              color:"#888", fontSize:14, fontWeight:600, cursor:"pointer" }}>Cancel</button>
          <button onClick={handleAdd} disabled={!name.trim()} style={{ flex:2, padding:"11px", borderRadius:10,
              background: name.trim() ? `linear-gradient(135deg,${color},${color}cc)` : "#222",
              border:"none", color: name.trim() ? "#fff" : "#444",
              fontSize:14, fontWeight:700, cursor: name.trim() ? "pointer" : "not-allowed" }}>
            {emoji} Add කරන්න
          </button>
        </div>
      </div>
    </div>
  );
}

// ── App ───────────────────────────────────────────────────────────────
export default function App() {
  const [items, setItems] = useState([
    { id: nextId++, name: "Meat Item 1", emoji: "🥩", color: "#FF6B35" },
  ]);
  const [showModal, setShowModal] = useState(false);
  // Store latest calc data per item id
  const [itemData, setItemData] = useState({});

  const addItem    = (item) => setItems(prev => [...prev, item]);
  const removeItem = (id)   => { setItems(prev => prev.filter(i => i.id !== id)); setItemData(prev => { const n={...prev}; delete n[id]; return n; }); };
  const onDataChange = useCallback((id, vals) => {
    setItemData(prev => ({ ...prev, [id]: vals }));
  }, []);

  const handlePDF = () => {
    const rows = items.map(item => {
      const d = itemData[item.id] || {};
      const price      = d.price      || 0;
      const iceWater   = d.iceWater   || 0;
      const otherWaste = d.otherWaste || 0;
      const quantity   = d.quantity   || 0;
      const calc = price > 0 ? calcItem({ price, iceWater, otherWaste, quantity }) : null;
      return { ...item, price, iceWater, otherWaste, quantity, calc };
    });
    generatePDF(rows);
  };

  const hasAnyData = items.some(i => itemData[i.id]?.price > 0);

  return (
    <div style={{ minHeight:"100vh", background:"#0d0d0d",
        backgroundImage:"radial-gradient(ellipse at 20% 20%,#1a0a00,transparent 55%),radial-gradient(ellipse at 80% 80%,#001a0d,transparent 55%)",
        fontFamily:"'DM Sans','Noto Sans Sinhala',sans-serif", padding:"40px 20px" }}>
      <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;600;700;800&family=Noto+Sans+Sinhala:wght@400;600;700&display=swap" rel="stylesheet" />

      {/* Header */}
      <div style={{ textAlign:"center", marginBottom:44 }}>
        <div style={{ display:"inline-block", fontSize:11, fontWeight:700, letterSpacing:3,
            color:"#FF6B35", textTransform:"uppercase", marginBottom:12,
            padding:"6px 16px", border:"1px solid #FF6B3533", borderRadius:20 }}>
          Waste Calculator
        </div>
        <h1 style={{ fontSize:"clamp(26px,5vw,44px)", fontWeight:800, color:"#fff",
            margin:"0 0 8px", letterSpacing:"-1.5px", lineHeight:1.1 }}>
          මාළු & මස් මිල{" "}
          <span style={{ background:"linear-gradient(135deg,#FF6B35,#E91E8C)",
              WebkitBackgroundClip:"text", WebkitTextFillColor:"transparent" }}>Calculator</span>
        </h1>
        <p style={{ color:"#444", fontSize:13, margin:"0 0 24px", fontFamily:"'Noto Sans Sinhala',sans-serif" }}>
          Gram වලින් waste දාන්න • Effective rate automatic ගණනය වෙයි
        </p>

        {/* Action buttons */}
        <div style={{ display:"flex", gap:12, justifyContent:"center", flexWrap:"wrap" }}>
          <button onClick={() => setShowModal(true)} style={{ padding:"12px 28px", borderRadius:12,
              background:"linear-gradient(135deg,#FF6B35,#E91E8C)", border:"none",
              color:"#fff", fontSize:14, fontWeight:700, cursor:"pointer",
              boxShadow:"0 4px 20px #FF6B3540", transition:"transform 0.15s" }}
            onMouseEnter={(e) => (e.currentTarget.style.transform="scale(1.04)")}
            onMouseLeave={(e) => (e.currentTarget.style.transform="scale(1)")}>
            + නව Item Add කරන්න
          </button>

          {hasAnyData && (
            <button onClick={handlePDF} style={{ padding:"12px 28px", borderRadius:12,
                background:"linear-gradient(135deg,#1a1a2e,#16213e)",
                border:"1px solid #ffffff22", color:"#fff",
                fontSize:14, fontWeight:700, cursor:"pointer",
                boxShadow:"0 4px 20px #00000040", transition:"transform 0.15s, box-shadow 0.15s",
                display:"flex", alignItems:"center", gap:8 }}
              onMouseEnter={(e) => { e.currentTarget.style.transform="scale(1.04)"; e.currentTarget.style.boxShadow="0 6px 28px #ffffff15"; }}
              onMouseLeave={(e) => { e.currentTarget.style.transform="scale(1)";    e.currentTarget.style.boxShadow="0 4px 20px #00000040"; }}>
              📄 PDF Report Download
            </button>
          )}
        </div>
      </div>

      {/* Cards */}
      {items.length === 0 ? (
        <div style={{ textAlign:"center", color:"#333", marginTop:60 }}>
          <div style={{ fontSize:48, marginBottom:12 }}>🥩</div>
          <div style={{ fontSize:14, fontFamily:"'Noto Sans Sinhala',sans-serif" }}>Items නැහැ — Add කරන්න!</div>
        </div>
      ) : (
        <div style={{ maxWidth:980, margin:"0 auto",
            display:"grid", gridTemplateColumns:"repeat(auto-fill,minmax(280px,1fr))", gap:22 }}>
          {items.map(item => (
            <ItemCard key={item.id} item={item} onRemove={removeItem} onDataChange={onDataChange} />
          ))}
        </div>
      )}

      {showModal && <AddItemModal onAdd={addItem} onClose={() => setShowModal(false)} />}
    </div>
  );
}
